AWSTemplateFormatVersion: "2010-09-09"
Description: "Serverless ETL Ingestion Resource Setup"
Resources:
  S3BucketSource:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties: 
      BucketName: source-data-lake
      PublicAccessBlockConfiguration: 
          BlockPublicAcls: TRUE
      Tags: [
        {"Key": "source-data-lake"}
      ]
      AccessControl: BucketOwnerFullControl

  S3BucketDest:
    Type: "AWS::S3::Bucket"
    DeletionPolicy: Delete
    Properties: 
      BucketName: dest-date-warehouse
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: TRUE
      Tags: [
        {"Key": "dest-data-lake"}
      ]

  SourceS3Policy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: source-data-lake
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
            - 's3:GetObject'
            - 's3:ListBucket'
          Effect: Allow
          Principal: '*'
          Resource:
            - 'arn:aws:s3:::source-data-lake'
            - 'arn:aws:s3:::source-data-lake/*'

  DestS3Policy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: dest-date-warehouse
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
            - 's3:PutObject'
            - 's3:GetObject'
          Effect: Allow
          Principal: '*'
          Resource:
            - 'arn:aws:s3:::dest-date-warehouse'
            - 'arn:aws:s3:::dest-date-warehouse/*'
