AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaMonitorS3Bucket:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_functions.trigger_handler
      Runtime: python3.7
